### ISSUE TITLE
Problem with TiSelectedCellBackgroundView and ARM64 architecture

### ISSUE THREAD

**Issue by francois-ubg** [nuno/TiCollectionView#22]
Hi,

Thanks for your job @mpociot !

When i try to compile for 64bit devices i have an error :

Titanium SDK vers : 3.5.0.GA and Module version 2.0

```
"_OBJC_CLASS_$_TiSelectedCellBackgroundView", referenced from:
objc-class-ref in libde.marcelpociot.collectionview.a(DeMarcelpociotCollectionviewCollectionItem.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried to add "Ti.UI.createRefreshControl({});" but i have the same problem...

``` javascript
Ti.UI.createRefreshControl({});
```

I can't distribute my application ...

Thanks for your help.

François

**Comment by TheBrousse** [comment]
It seems the problem only occurs on device. It works well in simulator.

**Comment by mpociot** [comment]
Well it's hard for me to reproduce this issue.

I'm using my module in an iPad app, that is already used in production, without having this issue.
So my guess would be that it somehow relates to the UI that is used.

It would be great if someone could provide me with some code to reproduce the bug.

**Comment by TheBrousse** [comment]
I have pushed the following test project (which is basically the test app using vers 1.2.0 of the module). It even fails on my simulator with Titanium 3.5.1.GA.

https://github.com/TheBrousse/collectiontester

Hope this helps

**Comment by thehollowearth** [comment]
I dont know if this is a requirement. But Author i.e.  Marcel Pociot should register this module at Appcelerator Marketplace and obviously we'd like if its available for free. It is possible that at the end step of xcodebuild while packaging/publishing the app, its connecting to internet and validating each module's validity and in such case if module is not present, it may be throwing some error. its just a hunch but i'm not sure that registering this module at Appcelerator Marketplace would fix it, but since author is unable to reproduce the error, may be this would be a start.

**Comment by nuno** [comment]
Seems very old, please reopen if needed
